require('address')
require('phone')
require('email')
require('contact')

Address.clear()
Phone.clear()
Email.clear()

$vaughns_address = Address.new({:street=> "123 Sesame Street", :city=> "New York", :state=> "NY", :zip=> "10036", :type=> "home"})
$vaughns_address.save()
$andrews_address = Address.new({:street=> "1600 Amphitheatre Parkway", :city=> "Mountain View", :state=> "CA", :zip=> "94043", :type=> "mothership"})
$andrews_address.save()
$mt_rushmore_address = Address.new({:street=> "13000 SD-244", :city=> "Keystone", :state=> "SD", :zip=> "57751", :type=> "office"})
$mt_rushmore_address.save()
$epicodus_address = Address.new({:street=> "208 SW 5th Avenue #105", :city=> "Portland", :state=> "OR", :zip=> "97204", :type=> "office"})
$epicodus_address.save()

$vaughns_phone_number = Phone.new({:area_code=>'303', :number=>'3333333', :type=>'cell'})
$vaughns_phone_number.save()
$andrews_phone_number = Phone.new({:area_code=>'404', :number=>'4444444', :type=>'fax'})
$andrews_phone_number.save()
$sallys_phone_number = Phone.new({:area_code=>'505', :number=>'5555555', :type=>'home'})
$sallys_phone_number.save()
$roberts_phone_number = Phone.new({:area_code=>'606', :number=>'6666666', :type=>'emergency'})
$roberts_phone_number.save()

$vaughns_email = Email.new({:address=>'vaughn@personal.com', :type=>'personal'})
$vaughns_email.save()
$andrews_email = Email.new({:address=>'andrew@work.com', :type=>'work'})
$andrews_email.save()
